/**
 * Auto-register all IPC services
 * This file is auto-generated by vite-plugin-auto-services.ts
 */

import "./agent.js";
import "./fs.js";
import "./git.js";
import "./oauth.js";
import "./os.js";
import "./posthog-analytics.js";
import "./posthog.js";
import "./shell.js";
import "./transcription-prompts.js";
import "./updates.js";
