/**
 * Auto-register all IPC services
 * This file is auto-generated by vite-plugin-auto-services.ts
 */

import "./dockBadge.js";
import "./fileWatcher.js";
import "./folders.js";
import "./fs.js";
import "./git.js";
import "./oauth.js";
import "./posthog-analytics.js";
import "./session-manager.js";
import "./settingsStore.js";
import "./shell.js";
import "./transcription-prompts.js";
import "./updates.js";
import "./worktree.js";
import "./worktreeUtils.js";
