/**
 * Auto-register all IPC services
 * This file is auto-generated by vite-plugin-auto-services.ts
 */

import "./git.js";
import "./posthog-analytics.js";
import "./session-manager.js";
import "./settingsStore.js";
import "./transcription-prompts.js";
